site_name: Markdown Nathan Etinzon Cefim
site_url: https://nathanetinzon.github.io/CEFIM
nav:
  - Home: index.md
  - Certificat IIS: AD-CS Certificat IIS.md
  - Certificat Apache: AD-CS Certificat Apache.md
  - Rudder: ITIL_Etinzon_Nathan.md