# Information sur le projet
site_name: Documentation Nathan Etinzon CEFIM
site_author: Nathan Etinzon
site_description: >-
	Site compilant la documentation faite par Nathan Etinzon dans le cadre de la formation au CEFIM.

#Copyright
copyright: Copyright &copy; 2023. Tous droits réservés Nathan Etinzon

#Icone
icon:
	logo: docs/img/favicon.ico

theme:
  name: material
  language: fr
  palette: 

    # Swtich pour mode nuit
    - scheme: slate
      toggle:
        icon: material/weather-night 
        name: Thème nuit

    # Swtich pour mode jour
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Thème jour
  features:
    - navigation.footer
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/nathan-etinzon-7006101b6/
nav:
  - Page d'accueil: index.md
  - Certificat IIS: AD-CS Certificat IIS.md
  - Certificat Apache: AD-CS Certificat Apache.md
  - Rudder: ITIL_Etinzon_Nathan.md