site_name: Documentation Nathan Etinzon CEFIM
theme:
  name: material
  language: fr
  palette: 

    # Swtich pour mode nuit
    - scheme: slate
      toggle:
        icon: material/weather-night 
        name: Thème nuit

    # Swtich pour mode jour
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Thème jour
nav:
  - Page d'accueil: index.md
  - Certificat IIS: AD-CS Certificat IIS.md
  - Certificat Apache: AD-CS Certificat Apache.md
  - Rudder: ITIL_Etinzon_Nathan.md